### ISSUE TITLE
GLIBC version problem

### ISSUE THREAD

**Issue by rose-jinyang** [PINTO0309/TensorflowLite-bin#10]
Hello
Thanks for contributing to this project.
I am going to use your prebuilt package on Ubuntu 18.04 aarch64.
But I met the following issue when importing tflite-runtime.

![image](https://user-images.githubusercontent.com/47862419/121848452-9c4cf680-cd1c-11eb-8668-724f51603ffe.png)

We have NEVER seen this issue when installing and using the Tensorflow python package.
Why does this problem occur when using your tflite-runtime package?
Could u provide the package for Ubuntu 18.04 aarch64?
Thanks

**Comment by PINTO0309** [comment]
Before we start the discussion, please tell us which script you used; Ubuntu 18.04 is old and has been removed from the build target for several versions now.

**Comment by PINTO0309** [comment]
And, If you are really on Ubuntu 18.04, then Python 3.6 and glibc2.27 is correct. Definitely, the binary that should be downloaded is wrong. 
https://github.com/PINTO0309/Tensorflow-bin#tensorflow-bin

**Comment by dev-srikanth** [comment]
I've encountered the same issue, still unable to find a way to fix this. @PINTO0309 could you please help fix the issue with installing tflite_runtime in ubuntu 18.04 aarch64?

**Comment by PINTO0309** [comment]
I'll say it again. You people are wrong.
