### ISSUE TITLE
'Interpreter' object has no attribute 'set_num_threads' 

### ISSUE THREAD

**Issue by auliaid** [PINTO0309/TensorflowLite-bin#11]
I have this error when run code in raspberry pi 4 (64bit os)

filename i used: **tflite_runtime-2.6.0-cp37-cp37m-linux_aarch64.whl**

I already add code below in interpreter.py (/usr/local/lib/python3.7/dist-packages/tflite_runtime) using nano.
    def set_num_threads(self, i):
    return self._interpreter.SetNumThreads(i)
    
But code still doesn't work.
Can you help me how to fix this issue?

**Comment by PINTO0309** [comment]
interpreter = Interpreter(model_path="foo.tflite", num_threads=4)
interpreter.allocate_tensors()

**Comment by auliaid** [comment]
> ```python
> interpreter = Interpreter(
>     model_path="foo.tflite",
>     num_threads=4
> )
> interpreter.allocate_tensors()
> ```

where do i add the code?
I have added it in interpreter.py but still the same error occurs.

**Comment by PINTO0309** [comment]
I don't know what you're talking about.

It is ready for inference as soon as you install it.

**Comment by PINTO0309** [comment]
```python
import argparse
import numpy as np
import time

from PIL import Image

from tflite_runtime.interpreter import Interpreter

def load_labels(filename):
  my_labels = []
  input_file = open(filename, 'r')
  for l in input_file:
    my_labels.append(l.strip())
  return my_labels
if __name__ == "__main__":
  floating_model = False
  parser = argparse.ArgumentParser()
  parser.add_argument("-i", "--image", default="/tmp/grace_hopper.bmp", \
    help="image to be classified")
  parser.add_argument("-m", "--model_file", \
    default="/tmp/mobilenet_v1_1.0_224_quant.tflite", \
    help=".tflite model to be executed")
  parser.add_argument("-l", "--label_file", default="/tmp/labels.txt", \
    help="name of file containing labels")
  parser.add_argument("--input_mean", default=127.5, help="input_mean")
  parser.add_argument("--input_std", default=127.5, \
    help="input standard deviation")
  parser.add_argument("--num_threads", default=1, help="number of threads")
  args = parser.parse_args()

  interpreter = Interpreter(model_path="foo.tflite", num_threads=4)
  interpreter.allocate_tensors()
  input_details = interpreter.get_input_details()
  output_details = interpreter.get_output_details()
  # check the type of the input tensor
  if input_details[0]['dtype'] == np.float32:
    floating_model = True
  # NxHxWxC, H:1, W:2
  height = input_details[0]['shape'][1]
  width = input_details[0]['shape'][2]
  img = Image.open(args.image)
  img = img.resize((width, height))
  # add N dim
  input_data = np.expand_dims(img, axis=0)
  if floating_model:
    input_data = (np.float32(input_data) - args.input_mean) / args.input_std

  interpreter.set_tensor(input_details[0]['index'], input_data)

  start_time = time.time()
  interpreter.invoke()
  stop_time = time.time()

  output_data = interpreter.get_tensor(output_details[0]['index'])
  results = np.squeeze(output_data)
  top_k = results.argsort()[-5:][::-1]
  labels = load_labels(args.label_file)
  for i in top_k:
    if floating_model:
      print('{0:08.6f}'.format(float(results[i]))+":", labels[i])
    else:
      print('{0:08.6f}'.format(float(results[i]/255.0))+":", labels[i])

  print("time: ", stop_time - start_time)
```

**Comment by PINTO0309** [comment]
Why do I need to modify interpreter.py? I would like to know what you are trying to do.

**Comment by PINTO0309** [comment]
Did you read the README?
https://github.com/PINTO0309/TensorflowLite-bin#operation-check-classification

**Comment by PINTO0309** [comment]
I really don't understand what you are trying to do, so all I can do is ask questions.

**Comment by auliaid** [comment]
I'm so sorry sir. I have a code like this. 

`import numpy as np
import math
import time
import sys
import cv2
import argparse

from tensorflow.lite.python.interpreter import Interpreter

fps = ""
detectfps = ""
framecount = 0
detectframecount = 0
time1 = 0
time2 = 0

LABELS = ['Adam','Adit','Bidin', 'Gilang', 'Icah' , 'Nugi', 'Pandu', 'Siwi']

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="detect.tflite", help="Path of the detection model.")
    parser.add_argument("--num_threads", type=int, default=4, help="Threads.")
    args = parser.parse_args()

    model        = args.model
    num_threads  = args.num_threads

    interpreter = Interpreter(model_path=model)
    interpreter.set_num_threads(num_threads)

    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    cam = cv2.VideoCapture(0)
    
    window_name = "Movie"
    cv2.namedWindow(window_name, cv2.WINDOW_AUTOSIZE)
    
    
    while True:
        start_time = time.perf_counter()

        ret, image = cam.read()
        
        # Resize and normalize image for network input
        image_height = image.shape[0]
        image_width = image.shape[1]
        frame = cv2.resize(image, (300, 300))
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = np.expand_dims(frame, axis=0)
        frame = frame.astype(np.float32)
        cv2.normalize(frame, frame, -1, 1, cv2.NORM_MINMAX)
        cv2.putText(image, fps, (image_width - 170, 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (38, 0, 255), 1, cv2.LINE_AA)
        cv2.putText(image, detectfps, (image_width - 170, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (38, 0, 255), 1, cv2.LINE_AA)

        # run model
        interpreter.set_tensor(input_details[0]['index'], frame)
        interpreter.invoke()

        # get results
        boxes = interpreter.get_tensor(output_details[0]['index'])[0]
        classes = interpreter.get_tensor(output_details[1]['index'])[0]
        scores = interpreter.get_tensor(output_details[2]['index'])[0]
        count = interpreter.get_tensor(output_details[3]['index'])[0]

        # draw boxes
        for i, (box, classidx, score) in enumerate(zip(boxes, classes, scores)):
            probability = score
            
            if probability >= 0.6:
                if not box[0] or not box[1] or not box[2] or not box[3]:
                    continue
                ymin = int(box[0] * image_height)
                xmin = int(box[1] * image_width)
                ymax = int(box[2] * image_height)
                xmax = int(box[3] * image_width)

                classnum = int(classidx)
                #print('coordinates: ({}, {})-({}, {}). class: "{}". probability: {:.2f}'.format(xmin, ymin, xmax, ymax, classnum, score))
                cv2.rectangle(image, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)
                cv2.putText(image, '{}: {:.2f}'.format(LABELS[classnum], score), (xmin, ymin - 5), cv2.FONT_HERSHEY_COMPLEX, 0.8, (255, 255, 0), 2)

        cow = cv2.resize(image, (720,480))
        cv2.imshow(window_name, cow)

        if cv2.waitKey(1)&0xFF == ord('q'):
            break

        detectframecount += 1

        # FPS calculation
        framecount += 1
        if framecount >= 10:
            fps = "(Playback) {:.1f} FPS".format(time1 / 10)
            detectfps = "(Detection) {:.1f} FPS".format(detectframecount / time2)
            framecount = 0
            detectframecount = 0
            time1 = 0
            time2 = 0
        end_time = time.perf_counter()
        elapsedTime = end_time - start_time
        time1 += 1 / elapsedTime
        time2 += elapsedTime
`

**Comment by auliaid** [comment]
I have this error when run code in raspberry pi 4 (64bit os).

'Interpreter' object has no attribute 'set_num_threads'

**Comment by PINTO0309** [comment]
Why don't you read my comments?

# NG
```python
    interpreter = Interpreter(model_path=model)
    interpreter.set_num_threads(num_threads)
```
# OK
```python
    interpreter = Interpreter(model_path=model, num_threads=args.num_threads)
```

**Comment by auliaid** [comment]
> Why don't you read my comments?
> 
> # NG
> ```python
>     interpreter = Interpreter(model_path=model)
>     interpreter.set_num_threads(num_threads)
> ```
> 
> # OK
> ```python
>     interpreter = Interpreter(model_path=model, num_threads=args.num_threads)
> ```

I so sorry sir my vocabulary is too bad..
My problem has been solved with the code you provided.
I will study harder, thank you very much for your help
