### ISSUE TITLE
TensorflowLite-bin on Ubuntu 18.04

### ISSUE THREAD

**Issue by a0917bc** [PINTO0309/TensorflowLite-bin#13]
### Issue Type

Feature Request

### OS

Ubuntu 18.04

### OS architecture

aarch64

### Hardware

RaspberryPi4

### Description

Hello, 

How do I use this [repository()](https://github.com/chandrikadeb7/Face-Mask-Detection) on raspberry pi 4(ubuntu18.04)?
I am already done with installing the package(TensorFlow 2.4.1) and finding a bottleneck on TensorFlow prediction(picture below).
How do I do with TensorflowLite?
I am sorry for describing my question, could you give me any suggestions? 

### Relevant Log Output

```shell
❯ python3 detect_mask_image.py --image images/pic1.jpeg
time:  11.797869443893433
❯ python3 detect_mask_image.py --image images/pic1.jpeg
time:  0.49208784103393555
```

**Comment by PINTO0309** [comment]
I have no idea what is wrong with the following execution log. Your explanation is too cursory. 
```
❯ python3 detect_mask_image.py --image images/pic1.jpeg
time:  11.797869443893433
❯ python3 detect_mask_image.py --image images/pic1.jpeg
time:  0.49208784103393555
```
This issue is completely unrelated to this repository in nature, so if your next answer is not understood by me, I will close it.

**Comment by PINTO0309** [comment]
Various optimized models have been committed. It is recommended that you install a 64-bit OS and use the latest version of TensorFlow or TensorFlow Lite.

- tflite, edgetpu, onnx, OpenVINO, Myriad, TFJS, CoreML.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/250_Face-Mask-Detection
