### ISSUE TITLE
Feature request: Prebuilt tflite-runtime for amd64

### ISSUE THREAD

**Issue by DanBmh** [PINTO0309/TensorflowLite-bin#17]
### Issue Type

Feature Request

### OS

Ubuntu 20.04

### OS architecture

Other

### Hardware

Other

### Description

I would like to use your prebuilt tflite-runtime on arm64 computers as well, so I would like to ask if you could provide prebuilt wheels for amd64 as well?

### Relevant Log Output

```shell
-
```

**Comment by PINTO0309** [comment]
I already own the x86_64 installer, but I dare not commit it because it goes against the purpose of this repository. If you need that runtime, just follow the README and build for an hour or so to get it.
https://github.com/PINTO0309/TensorflowLite-bin#2-tensorflow-v230-version-or-later

e.g.
- For aarch64
```
### Python 3.8
sudo CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3.8 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.8" \
  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64
```
- For x86_64 (amd)
```
### Python 3.8
sudo CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3.8 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.8" \
  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh
```

**Comment by DanBmh** [comment]
Note for future readers: The wheel can afterwards be found at: `./tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.8/dist/`

**Comment by DanBmh** [comment]
@PINTO0309 even though the newly built runtime supports and loads XNNPACK (unlike the version from coral) I don't see a difference in prediction times. And in direct comparison with `tf.lite` runtime it's about 8x slower. Did you have the same experience with your installer?

**Comment by PINTO0309** [comment]
x86_64 (amd) is not suitable for INT8 processing. Inference with Float32 is 10 times faster than with INT8.
