### ISSUE TITLE
'Interpreter' object has no attribute 'set_num_threads'

### ISSUE THREAD

**Issue by alexkrayniy** [PINTO0309/TensorflowLite-bin#3]
I have this error when run you code in reaspberry pi4.
Can you help me how to fix this issue?

**Comment by PINTO0309** [comment]
What is the name of the .whl file you used for the installation?

**Comment by alexkrayniy** [comment]
sudo pip3 install --upgrade tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl
I have used it

**Comment by alexkrayniy** [comment]
$ sudo apt install swig libjpeg-dev zlib1g-dev python3-dev python3-numpy unzip
$ wget https://github.com/PINTO0309/TensorflowLite-bin/raw/master/1.15.0/tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl
$ sudo pip3 install --upgrade tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl

**Comment by PINTO0309** [comment]
Checking the contents of the .whl file, it seems that the set_num_threads method is implemented. I will check a little when I come home, but I will start working 10 hours later. While waiting for my findings, try uninstalling and reinstalling.

![setnumthreads](https://user-images.githubusercontent.com/33194443/72864066-2191ce80-3d16-11ea-9439-b459e98fc31c.png)
![whl](https://user-images.githubusercontent.com/33194443/72864069-25bdec00-3d16-11ea-9c36-752ad4c9af4a.png)

**Comment by alexkrayniy** [comment]
After I add it, it is working now.
Thank you
