### ISSUE TITLE
1.15.0 install

### ISSUE THREAD

**Issue by StuartIanNaylor** [PINTO0309/TensorflowLite-bin#5]
pi@raspberrypi:~ $ pip3 install tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/lib/python3/dist-packages/pip/_internal/download.py", line 823, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/download.py", line 728, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 600, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 485, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Same with 1.5.1 prob me but apols :)

**Comment by PINTO0309** [comment]
Doesn't the situation change after running the following command?
```console:
$ sudo apt-get update && sudo apt-get upgrade
$ wget https://github.com/PINTO0309/TensorflowLite-bin/raw/master/1.15.0/tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl
$ sudo pip3 install tflite_runtime-1.15.0-cp37-cp37m-linux_armv7l.whl
```

**Comment by StuartIanNaylor** [comment]
Yes and confused but wow thanks for the quick reply

**Comment by PINTO0309** [comment]
Please tell me the results below.
```console
$ pip3 -V
$ sudo pip3 install pip --upgrade
```

**Comment by StuartIanNaylor** [comment]
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/2e/df11ea7e23e7e761d484ed3740285a34e38548cf2bad2bed3dd5768ec8b9/pip-20.1-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 208kB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-20.1

**Comment by StuartIanNaylor** [comment]
I was just playing with deepspeech .7
Noticed it seemed to be predominantly single thread did a google and happened to find your repo.
After runing it now seems to be multithread some of the time but makes little difference in operation.
Not any criticism but just wondered if you had any ideas why?
Does the memory movement to threads cancel out the benefit?

**Comment by PINTO0309** [comment]
You will not get the best performance unless you install a 64-bit OS. On Raspbian it will make little difference. Also, the effect of multithreading is not exerted on all models. Please read carefully the closed issues and RDADME. I'm sure it will be useful for you. Benchmark results from me and engineers from all over the world show up to 2.5x better performance with 4 threads.

**Comment by PINTO0309** [comment]
By the way, you need to uninstall 1.15.1 first.
sudo pip3 uninstall tflite-runtime

**Comment by StuartIanNaylor** [comment]
Lols after all that Mozilla have there own fork.
https://github.com/mozilla/tensorflow

PS doesn't seem to install on Ubuntu 64 but worked fine on Debian.
Tried 18.04 & 20.04 and kept saying doesn't support.

**Comment by PINTO0309** [comment]
>Tried 18.04 & 20.04 and kept saying doesn't support.

The results you've taught me are correct. Because the versions of glibc and Python are different for different OS versions, the installer I created cannot be used in other environments except glibc 2.28 and Python 3.7. 

1. **[https://github.com/PINTO0309/Tensorflow-bin/issues/21, Do i need 3.7.3 ?](https://github.com/PINTO0309/Tensorflow-bin/issues/21)**
2. **[https://github.com/PINTO0309/Tensorflow-bin/issues/17#issuecomment-602258906, 'GLIBC_2.29' error not found for Python 3.7 + Tensorflow v2](https://github.com/PINTO0309/Tensorflow-bin/issues/17)**

It's easy to compile on your own. First, please make the following corrections.

- tensorflow/lite/python/interpreter.py
```bash
# Add the following two lines to the last line
  def set_num_threads(self, i):
    return self._interpreter.SetNumThreads(i)
```
- tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc
```C++
// Corrected the vicinity of the last line as follows
PyObject* InterpreterWrapper::ResetVariableTensors() {
  TFLITE_PY_ENSURE_VALID_INTERPRETER();
  TFLITE_PY_CHECK(interpreter_->ResetVariableTensors());
  Py_RETURN_NONE;
}

PyObject* InterpreterWrapper::SetNumThreads(int i) {
  interpreter_->SetNumThreads(i);
  Py_RETURN_NONE;
}

}  // namespace interpreter_wrapper
}  // namespace tflite
```
- tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.h

```C++
  // should be the interpreter object providing the memory.
  PyObject* tensor(PyObject* base_object, int i);

  PyObject* SetNumThreads(int i);

 private:
  // Helper function to construct an `InterpreterWrapper` object.
  // It only returns InterpreterWrapper if it can construct an `Interpreter`.
```
Next, I think it's just a matter of changing the Docker Image in the tutorial below to the OS you want to use by yourself.
**https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package**

**Comment by StuartIanNaylor** [comment]
Hey many thanks as might give that a go as Ubuntu seem to be quite strong on Pi images now.
Only thing I dislike is the preloaded snap and cloud bumf which wish wasn't there.

Things have sort of come derailed as was wondering if maybe there was a happy point with Mozilla DeepSpeech as it doesn't work multithread with TFLite.
If you got the perf increase you generally get of x2.5 then a Pi3 would be able to run just faster than realtime.
Unfortunately not though and all you get is replies such as "As documented, TFLite runtime does not leverage threads due to TensorFlow-level limitations with our model." but actually finding why or where its documented is much harder.
Think they might be a bit sensitive to comments on this so suggest not posting.
https://discourse.mozilla.org/t/deepspeech-tensorflow-does-not-use-all-cpu-cores/32790/14

**Comment by PINTO0309** [comment]
I forgot to tell you something important. Tensorflow Lite's model .tflite performs best on ARM 64bit CPU + 64bit OS with Integer Quantization. The following URL is a sample of the object detection behavior of the .tflite model with Integer Quantization. All of these are the results of reasoning with the RaspberryPi4 CPU only. If the model you used for validation is not quantized, you won't get much out of it.

1. **https://github.com/PINTO0309/PINTO_model_zoo#sample1---object-detection-by-video-file**
2. **https://github.com/PINTO0309/PINTO_model_zoo#sample2---object-detection-by-usb-camera**
3. **https://github.com/PINTO0309/PINTO_model_zoo#sample3---head-pose-estimation-multi-stage-inference-with-multi-model**

**Comment by StuartIanNaylor** [comment]
Thats brilliant and thanks.

PS presuming if fed with MFCC spectrograms then voice could work on the same procedures?
Really interested in binary KWS of 'is keyword' & 'not keyword' classification and methods to increase accuracy of simple binary classification.
I am not really worthy of your brilliant input as no where near your level of knowledge and many thanks for all the Pi fixes you provide.

**Comment by PINTO0309** [comment]
If you can provide me with a trained checkpoint it is possible to give it a try. Alternatively, you can try it if you provide .tflite

**Comment by StuartIanNaylor** [comment]
Prob pointless at this time as have just been using the basic tutorial https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands

Also in the examples is https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/wav_to_spectrogram

The spectograms it uses I have a hunch are pretty ropey, in fact they are pretty terrible.
There is a really good article on this  https://blog.aspiresys.pl/technology/building-jarvis-nlp-hot-word-detection/ 
That uses librosa which provides much better mfcc spectograms https://librosa.github.io/librosa/generated/librosa.feature.mfcc.html#librosa.feature.mfcc

The above blog is a great introduction and the source code it provides is great.
https://github.com/nekon1987/fpool3-keras-implementation

So not even there yet as still trying to work out with librosa which is also excellent but as mentioned in https://en.wikipedia.org/wiki/Mel-frequency_cepstrum#Noise_sensitivity
I think that is really important to implement S:np.ndarray [shape=(d, t)] as 'barge in' with noise is really important with voice.
Thinking its likely its already done and documented
```
def extract_audio_features(self):
    audio, sample_rate = librosa.load(self.file_path, sr=self.sample_rate, res_type='kaiser_best')
    self.mfcc = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    self.mfccScaled = np.mean(self.mfcc.T, axis=0)
```

But also I am beginning to wonder unlike image recognition voice is actually much easier because the recognition object is already known which is our voice.
I keep thinking with the advent of 'cloud tpu' access a general model should supplied which I have been building from the google command dataset for now, but the easiest way to increase accuracy is to include your voice in that dataset and that a period of training data collection should take place that may prompt for a model update.

https://cloud.google.com/tpu/pricing

**Comment by PINTO0309** [comment]
I've been very busy with my day job and I've been very slow to reply. I will next try to quantize the .tflite below. It seems to be a very special model, so I'm not sure if it will work.
## DeepSpeech 0.7.1
**https://github.com/mozilla/DeepSpeech/releases**

**Comment by StuartIanNaylor** [comment]
Cheers Pinto no pressure and only if it interests. I am not really sure what they are doing with that model as it will only run single thread which on lower harder such as a Pi3 means its quite slow.
It takes a Pi4 to be able to go faster than realtime and only just.

**Comment by PINTO0309** [comment]
I am considering other means. Closed for now.
