### ISSUE TITLE
Add .whl-binary for TensorflowLite 2.5.0 for Python 3.8 (Ubuntu 20.10)

### ISSUE THREAD

**Issue by vak** [PINTO0309/TensorflowLite-bin#6]
Many thanks for your contributions!

is it possible to add a whl-binary for TensorflowLite 2.5.0 for Python 3.8 (Ubuntu 20.10) ?

Reasons:
1. tflite is already v2.5.0
2. installing Python3.7 on Raspberry Pi4 running Ubuntu 20.10  is a bit tricky, but Python3.8 is already there! :-)

**Comment by PINTO0309** [comment]
Supposedly there will be an official release of v2.4.0 next week. There are no plans to build and commit the master(main) branch at the moment.

If you're in a hurry, you can generate it in about an hour by simply running the following command.
```console
sudo CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3.8 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.8" \
  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64

sudo CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3.8 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.8" \
  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh armhf
```

**Comment by vak** [comment]
many thanks for the quick answer!

I saw this your advice on README.md already, but I didn't understand how your multithreading support could come into play if we compile from original Google's tensorflow lite, which doesn't have it. 

Or did I misunderstand here something?

**Comment by PINTO0309** [comment]
Fortunately, multi-threading support has been officially incorporated in v2.3.0. You don't need to do any special operations when building.

**Comment by vak** [comment]
hm... but I was trying to use [official WHLs](https://www.tensorflow.org/lite/guide/python) with `num_threads` and failed.

Albeit, I used official WHL-binary having version **2.5.0** for ARM64 Python3.8. Really strange.

P.S. BTW, your work is awesome cool !

**Comment by PINTO0309** [comment]
Tell me the architecture. aarch64 or armhf

**Comment by PINTO0309** [comment]
aarch64？

**Comment by vak** [comment]
@PINTO0309 Oh, `Interpreter(, num_threads=4)` is now working on official Google's WHL indeed! 

i am on aarch64 (Raspberry Pi 4 B, Ubuntu 20.10 64-bit)

**Comment by vak** [comment]
@PINTO0309 many thanks!
