### ISSUE TITLE
Python inference example on ARM GPU

### ISSUE THREAD

**Issue by rose-jinyang** [PINTO0309/TensorflowLite-bin#7]
Hello
How are you?
Thanks for contributing to this project.
I am going to use Python tflite inference using Mali GPU on RK3399 Ubuntu 18.04 aarch64.
Do your prebuilt packages support OpenCL on ARM GPU?
if so, could u provide an example for Python inference on ARM GPU?
Thanks

**Comment by PINTO0309** [comment]
Unfortunately, no.
